packages:
  - apps/*
  - api
  - cre
  - cre/commitpass
  - indexer
  - packages/*
  - contracts

catalog:
  "@types/node": 24.19.0
  typescript: 5.9.3

onlyBuiltDependencies:
  - sharp
  - unrs-resolver

supportedArchitectures:
  cpu: [current]
  os: [current, linux]
