testnet-settings:
  user-workflow:
    workflow-name: commitpass-lifecycle-testnet
  workflow-artifacts:
    workflow-path: ./main.ts
    config-path: ./config.testnet.json
    secrets-path: ../secrets.yaml
local-settings:
  user-workflow:
    workflow-name: commitpass-lifecycle-local
  workflow-artifacts:
    workflow-path: ./main.ts
    config-path: ../.local/config.json
    secrets-path: ../secrets.example.yaml
