import { mkdir, readFile, writeFile } from "node:fs/promises";

const root = new URL("../../../", import.meta.url);
await mkdir(new URL("indexer/abi/", root), { recursive: true });
for (const contract of ["CommitPassFactory", "CommitPassVault"]) {
  const abi = await readFile(
    new URL(`packages/shared/abi/${contract}.json`, root),
  );
  await writeFile(new URL(`indexer/abi/${contract}.json`, root), abi);
}
const manifest = JSON.parse(
  await readFile(
    new URL("packages/shared/src/deployments/monad-testnet.json", root),
    "utf8",
  ),
);
await writeFile(
  new URL("indexer/deployment.json", root),
  JSON.stringify(manifest, null, 2) + "\n",
);
const config = await readFile(new URL("indexer/config.yaml", root), "utf8");
// Cloud builds only the indexer root; every ABI and import must live inside it.
await writeFile(
  new URL("indexer/config.hosted.yaml", root),
  "# Generated by packages/shared/tools/export-indexer.mjs from the active manifest.\n" +
    config
      .replace("${ENVIO_START_BLOCK:-0}", String(manifest.startBlock))
      .replace(
        "${ENVIO_FACTORY_ADDRESS:-0x0000000000000000000000000000000000000000}",
        manifest.contracts.CommitPassFactory.address,
      )
      .replace(
        "${ENVIO_RPC_URL:-https://testnet-rpc.monad.xyz}",
        "https://testnet-rpc.monad.xyz",
      ),
);
